# Generated by Django 5.2.8 on 2025-11-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('beneficios', models.CharField(max_length=10000)),
                ('destaque', models.BooleanField(default=True)),
            ],
        ),
    ]
