# Generated by Django 5.2.8 on 2025-11-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
