# Generated by Django 5.2.8 on 2025-11-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plano_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
