# Generated by Django 5.2.8 on 2025-11-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_plano_destaque_alter_plano_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
